Repository StackStorm/stackstorm.com, pull requests merged in 2022-08, with the labels that each got.

#6 Fix: #1 "Get Started" buttons on homepage not working
  index.html
Labels: bug, enhancement

#12 Add basic docker-compose file for a local web development
  README.md
  docker-compose.yml
Labels: enhancement

#11 Add Orchestral Case Study page to StackStorm website and add a Partner page URL
  case-studies/index.html
  case-study-orchestral/images/520x520-05.png
  case-study-orchestral/images/Bharath.png
  case-study-orchestral/images/BharathYadla.png
  case-study-orchestral/images/DSmith.png
  case-study-orchestral/images/Dimitri.png
  case-study-orchestral/images/DimitriZimine.png
  case-study-orchestral/images/Orchestral.ai_full_logo-1000x525.png
  case-study-orchestral/images/Orchestral.ai_full_logo-1024x538.png
  case-study-orchestral/images/Orchestral.ai_full_logo-150x79.png
  case-study-orchestral/images/Orchestral.ai_full_logo-220x116.png
  case-study-orchestral/images/Orchestral.ai_full_logo-250x131.png
  case-study-orchestral/images/Orchestral.ai_full_logo-280x147.png
  case-study-orchestral/images/Orchestral.ai_full_logo-300x158.png
  case-study-orchestral/images/Orchestral.ai_full_logo-510x268.png
  case-study-orchestral/images/Orchestral.ai_full_logo-750x394.png
  case-study-orchestral/images/Orchestral.ai_full_logo-768x403 copy.png
  case-study-orchestral/images/Orchestral.ai_full_logo-768x403.png
  case-study-orchestral/images/Orchestral.ai_full_logo-80x42.png
  case-study-orchestral/images/Orchestral.ai_full_logo-975x512.png
  case-study-orchestral/images/Orchestral.ai_full_logo.png
  case-study-orchestral/images/StuartEvans.png
  case-study-orchestral/images/cropped-ICON-INSIDE-WHITE_512x512-180x180.png
  case-study-orchestral/images/cropped-ICON-INSIDE-WHITE_512x512-192x192.png
  case-study-orchestral/images/cropped-ICON-INSIDE-WHITE_512x512-270x270.png
  case-study-orchestral/images/cropped-ICON-INSIDE-WHITE_512x512-32x32.png
  case-study-orchestral/images/evans-stuart.png
  case-study-orchestral/images/stackstorm-partners-150x30.png
  case-study-orchestral/images/stackstorm-partners-220x43.png
  case-study-orchestral/images/stackstorm-partners-250x49.png
  case-study-orchestral/images/stackstorm-partners-280x55.png
  case-study-orchestral/images/stackstorm-partners-300x59.png
  case-study-orchestral/images/stackstorm-partners-510x101-1-300x59.png
  case-study-orchestral/images/stackstorm-partners-510x101-1.png
  case-study-orchestral/images/stackstorm-partners-510x101.png
  case-study-orchestral/images/stackstorm-partners-750x148.png
  case-study-orchestral/images/stackstorm-partners-768x152.png
  case-study-orchestral/images/stackstorm-partners-80x16.png
  case-study-orchestral/images/stackstorm-partners.png
  case-study-orchestral/index.html
  partners/index.html
  stackstorm-thought-leaders/index.html
Labels: partners
